version: '3.4'

services:
  clientdatamanagement:
    image: clientdatamanagement
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=UHKS0124UAT;Database=UOBCMS;User Id=TestingDev;Password=aa00pp11;Encrypt=False;TrustServerCertificate=True;